spring:
  application:
    name: sc-gateway-sample
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 18090
management:
  server:
    port: 18091
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: 'http://127.0.0.1:18080/eureka/'
    register-with-eureka: false
