spring:
  application:
    name: bar-service
eureka:
  client:
    service-url:
      defaultZone: 'http://127.0.0.1:8761/eureka/'
server:
  port: 8081
management:
  server:
    port: 18081
  endpoints:
    web:
      exposure:
        include: '*'
swagger:
  base-package: com.github.taccisum.swagger.aggregation.sample.app
